i did the swiper component
WildCodeSchool/0923-lille-JS-eatingnamnam pull request #12
Opened 2024-01-03 12:34 UTC by NemoOnTheNet

2024-01-03 13:44 UTC, Thomas-Nigon approved these changes

2024-01-03 14:22 UTC, Sax593 requested changes

2024-01-03 14:22 UTC, Sax593 commented on frontend/src/components/Swipper/Swipper.scss
> +
Unnecessary space

2024-01-03 14:22 UTC, Sax593 commented on frontend/src/components/StarBar/StarBar.jsx
>        <img src="src/assets/star.svg" alt="" />
No empty alt

2024-01-04 07:08 UTC, Sax593 approved these changes

2024-01-04 07:48 UTC, merged