Composant   2.6   commentaires
WildCodeSchool/0923-lille-JS-eatingnamnam pull request #31
Opened 2024-01-09 15:19 UTC by TICONFRED27

2024-01-09 15:36 UTC, Marie-Sail requested changes

2024-01-09 15:36 UTC, Marie-Sail commented on frontend/src/components/CommentCard/CommentCard.jsx
> +    <div className="thecomment">
Mettre en camelcase ou juste l'appeler comments

2024-01-09 15:36 UTC, Marie-Sail commented on frontend/src/components/CommentCard/CommentCard.jsx
> +      <div className="flex-container">
utilise la methode BEM

2024-01-09 15:36 UTC, Marie-Sail commented on frontend/src/components/CommentCard/CommentCard.jsx
> +    <div className="thecomment">
ne pas oublier de changer les autres classe qui en découle

2024-01-09 15:36 UTC, Marie-Sail commented on frontend/src/components/CommentCard/CommentCard.scss
> +.thecomment {
change avec le nouveau nom

2024-01-09 15:36 UTC, Marie-Sail commented on frontend/src/components/CommentCard/CommentCard.scss
> +.flex-container {
change avec le nouveau nom

2024-01-09 15:55 UTC, Marie-Sail approved these changes

2024-01-10 08:21 UTC, NemoOnTheNet approved these changes

2024-01-10 09:29 UTC, fantinerudent approved these changes

2024-01-10 09:40 UTC, merged