Recipe ingredients
WildCodeSchool/0923-lille-JS-eatingnamnam pull request #36
Opened 2024-01-10 15:34 UTC by NemoOnTheNet

2024-01-10 16:09 UTC, Thomas-Nigon approved these changes

2024-01-11 08:29 UTC, Marie-Sail requested changes

2024-01-11 08:29 UTC, Marie-Sail commented on frontend/src/components/IngredientCard/IngredientCard.scss
> +    background-color: blue;
background à enlever

2024-01-11 08:40 UTC, Marie-Sail approved these changes

2024-01-11 08:49 UTC, fantinerudent approved these changes

2024-01-11 08:58 UTC, merged